# Generated by Django 5.0.4 on 2024-04-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='dep_name',
            field=models.CharField(choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('EXE', 'EXE'), ('IT', 'IT'), ('ME', 'ME'), ('MI/ML', 'MI/ML')], max_length=100, verbose_name='Name'),
        ),
    ]
